### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by heudenbach** [bashclub/check-opnsense#2]
Hello, thanks for this great OPNSense Check - i get the following error (running OPNSense )

Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 104, in do_checks
    _lines += getattr(self,_check)()
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 589, in checklocal_acmeclient
    if _cert_info.get("enabled") != "1":
AttributeError: 'str' object has no attribute 'get'

Running:
OPNSense 21.10-amd64
FreeBSD 12.1
OpenSSL 1.1.1l24

**Comment by heudenbach** [comment]
seems resolved with version 0.69 - thanks!
