### ISSUE TITLE
OPNsense, Failed to execute python plugins: ipsec

### ISSUE THREAD

**Issue by FingerlessGlov3s** [bashclub/check-opnsense#34]
Hi,

I used to have IPsec tunnel configured but it's been deleted both P1/P2 and IPsec disabled. But the plugin is still trying to execute it's checks for IPsec. Traceback below

```
Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 231, in do_checks
    _lines += getattr(self,_check)()
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 918, in checklocal_ipsec
    _ikeid = _phase1.get("ikeid")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by tzockt** [comment]
I have a similar problem:

```
Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 239, in do_checks
    _lines += getattr(self,_check)()
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 945, in checklocal_ipsec
    if len(_name.strip()) < 1:
AttributeError: 'NoneType' object has no attribute 'strip'
```
@thorstenspille Any ideas?

**Comment by remcomldr** [comment]
I also have the same issue:
`AttributeError: 'NoneType' object has no attribute 'strip'`

**Comment by xentity** [comment]
hey there,

had the same problem. Changed the lines as follows:

```
   1029         for _phase1 in _phase1config:
   1030             if _phase1 == None:
   1031                 continue
   1032             _ikeid = _phase1.get("ikeid")
   1033             _name = _phase1.get("descr")
   1034             if not _name or len(_name.strip()) < 1:             <<<<<<<<<
   1035                 _name = _phase1.get("remote-gateway")
   1036             _condata = _json_data.get(f"con{_ikeid}",{})
```

I'm not familiar with pull requests. Do you have a good tutorial?
